### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by webnah** [FRFirdaus/sale_shopee#1]
![image](https://user-images.githubusercontent.com/46319124/147300904-96cbc221-9acf-4f29-a767-e1813a3eab67.png)

please help

**Comment by webnah** [comment]
![image](https://user-images.githubusercontent.com/46319124/147300883-0da60693-bbc4-46ff-b593-897bda6c6f9a.png)

**Comment by webnah** [comment]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/Users/vuthang/dev/python/odoo-14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/Users/vuthang/dev/python/odoo-14/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/Users/vuthang/dev/python/odoo-14/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/vuthang/dev/python/odoo-14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/vuthang/dev/python/odoo-14/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/vuthang/dev/python/odoo-14/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/Users/vuthang/dev/python/odoo-14/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/Users/vuthang/dev/python/odoo-14/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/Users/vuthang/dev/python/odoo-14/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/vuthang/dev/python/odoo-14/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/Users/vuthang/dev/python/odoo-14/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/Users/vuthang/dev/python/odoo-14/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/Users/vuthang/dev/python/odoo-14/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/vuthang/dev/python/odoo-14/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/vuthang/dev/python/odoo-14/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/vuthang/dev/python/odoo-14/odoo/modules/loading.py", line 460, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/Users/vuthang/dev/python/odoo-14/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/Users/vuthang/dev/python/odoo-14/odoo/modules/loading.py", line 197, in load_module_graph
    registry.setup_models(cr)
  File "/Users/vuthang/dev/python/odoo-14/odoo/modules/registry.py", line 273, in setup_models
    model._setup_base()
  File "/Users/vuthang/dev/python/odoo-14/odoo/models.py", line 2787, in _setup_base
    self._add_field(name, field.new())
  File "/Users/vuthang/dev/python/odoo-14/odoo/models.py", line 404, in _add_field
    field.setup_base(self, name)
  File "/Users/vuthang/dev/python/odoo-14/odoo/fields.py", line 280, in setup_base
    self._setup_regular_base(model)
  File "/Users/vuthang/dev/python/odoo-14/odoo/fields.py", line 2268, in _setup_regular_base
    "Field %s with non-str value in selection" % self
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vuthang/dev/python/odoo-14/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/vuthang/dev/python/odoo-14/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AssertionError: Field merchant.shopee.order_interval with non-str value in selection

**Comment by FRFirdaus** [comment]
hey this is available only on odoo 12 thank you.. from what i see you just need to change selection field key value
```
INTERVAL_GET_ORDER = [
    (3, "3 days before from current date"),
    (2, "2 days before from current date"),
    (1, "1 days before from current date"),
    (0, "Custom Interval Date")
]
```
from integer to string since odoo 14 only used string for their selection key, note that you also need to change the code adapted to odoo 14 with new key of selection field
